# Generated by Django 3.1.4 on 2020-12-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('channelId', models.CharField(max_length=30)),
                ('channelTitle', models.CharField(max_length=100)),
                ('channelKind', models.TextField()),
                ('channelRegion', models.CharField(max_length=10)),
                ('channelLogoD', models.URLField()),
                ('channelLogoM', models.URLField()),
                ('channelLogoH', models.URLField()),
                ('channelDescription', models.TextField(blank=True, null=True)),
                ('channelSubscriberCount', models.BigIntegerField()),
                ('channelViewCount', models.BigIntegerField()),
                ('channelVideoCount', models.IntegerField(blank=True, null=True)),
                ('channelPublishedAt', models.CharField(max_length=30)),
            ],
        ),
    ]
