# Generated by Django 3.1.4 on 2020-12-02 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelTotalData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdDate', models.DateField(auto_now=True)),
                ('channelId', models.CharField(max_length=30)),
                ('channelTitle', models.CharField(max_length=100)),
                ('channelSubscriberCount', models.BigIntegerField()),
                ('channelViewCount', models.BigIntegerField()),
                ('channelVideoCount', models.IntegerField(blank=True, null=True)),
                ('channelowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.creator')),
            ],
        ),
    ]
