# Generated by Django 3.1.4 on 2020-12-04 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ydotdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channeltotaldata',
            name='channelId',
        ),
        migrations.RemoveField(
            model_name='channeltotaldata',
            name='channelSubscriberCount',
        ),
        migrations.RemoveField(
            model_name='channeltotaldata',
            name='channelTitle',
        ),
        migrations.RemoveField(
            model_name='channeltotaldata',
            name='channelVideoCount',
        ),
        migrations.RemoveField(
            model_name='channeltotaldata',
            name='channelViewCount',
        ),
        migrations.RemoveField(
            model_name='channeltotaldata',
            name='createdDate',
        ),
    ]
