# Generated by Django 3.1.4 on 2020-12-04 07:25

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('ydotdata', '0002_auto_20201204_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='channeltotaldata',
            name='attrs',
            field=django_mysql.models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='channeltotaldata',
            name='createdDate',
            field=models.DateField(auto_now=True),
        ),
    ]
