# Generated by Django 3.1.4 on 2020-12-29 08:59

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('ydotdata', '0003_auto_20201204_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelId', models.CharField(blank=True, max_length=30, null=True)),
                ('channelTitle', models.CharField(max_length=100)),
                ('logData', django_mysql.models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
